version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 1
