name: Deploy WebApp on merge
'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get && dart run build_runner build --delete-conflicting-outputs --release

      - name: Build Flutter web
        run: flutter build web --web-renderer canvaskit
